routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::middleware(['middleware'=>'back'])->group(function (){
    Auth::routes([
        'register'=>false
    ]);
});

//Route::group(['prefix'=>'doctor','middleware'=>['auth','doctor']], function (){
    Route::get('/doctor',[\App\Http\Controllers\HomeController::class, 'doctorpanel'])->name('doctorpanel');
    Route::resource('/doctor/recipe', \App\Http\Controllers\Doctor\RecipeController::class);
    Route::get('/doctor/base', [\App\Http\Controllers\Doctor\RecipeController::class, 'drug_views'])->name('drug.view');
//});
Route::get('/drug/from/{recipe}',[\App\Http\Controllers\Doctor\RecipeController::class, 'show_drug'])->name('show.retsept');
Route::get('/drug/sell/{recipe}', [\App\Http\Controllers\Doctor\RecipeController::class, 'drug_update'])->name('sell.drug');



Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Recipe.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Recipe extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'alogin',
        'password',
        'role',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/Doctor/RecipeController.php
<?php

namespace App\Http\Controllers\Doctor;

use App\Http\Controllers\Controller;
use App\Models\Recipe;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

class RecipeController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $recipes = DB::select("select recipes.id as asosiy,recipes.drug_name,recipes.drug_doze,recipes.drug_count,recipes.patient,recipes.recipe_qrcode,recipes.qrcode_scan,drugs.id as ikki, drugs.id, drugs.drug_title, drugs.drug_all from recipes inner join drugs on recipes.drug_name=drugs.id");
//        dd($recipes);
        return view('doctors.recipe.index', compact('recipes'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $drugs = DB::select("select * from drugs");
        return view('doctors.recipe.create', compact('drugs'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {


        $recipes = new Recipe();
        $recipes->drug_name = $request->drug_name;
        $recipes->drug_doze = $request->drug_doze;
        $recipes->drug_count = $request->drug_count;
        $recipes->patient = $request->patient;
        $qr_name = uniqid().".svg";
        $recipes->recipe_qrcode	= $qr_name;
        $recipes->qrcode_scan = 0;
        $recipes->save();
//        QrCode::size(300)->format('png')->generate(route('show.retsept',$recipes->id), public_path('doctors/qrcodes/'.$qr_name));
        return redirect()->route('recipe.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }

    public function show_drug(Recipe $recipe)
    {
//        dd($recipe);
        $retseptlar = DB::select("select recipes.id as asosiy,recipes.drug_name,recipes.drug_doze,recipes.drug_count,recipes.patient,recipes.recipe_qrcode,recipes.qrcode_scan,drugs.id as ikki, drugs.id, drugs.drug_title, drugs.drug_all from recipes inner join drugs on recipes.drug_name=drugs.id where recipes.id=?",[$recipe->id]);
//        dd($retseptlar[0]);
        return view('main.view', compact('retseptlar'));
    }

    public function drug_views()
    {
        $drugs = DB::select("select * from drugs");
        return view('doctors.drug.index', compact('drugs'));
    }

    public function drug_update(Recipe $recipe)
    {
//        dd($recipe);
        $sell_drug = $recipe->drug_count;
        $base_count = DB::select("select drug_all from drugs where id=?",[$recipe->drug_name]);
        $result = $base_count[0]->drug_all-$sell_drug;
//        dd($result);
        DB::select("update drugs set drug_all=? where id=?",[$result,$recipe->drug_name]);
        DB::select("update recipes set qrcode_scan=1 where id=?",[$recipe->id]);
        return redirect()->route('recipe.index');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function doctorpanel()
    {
        return view('doctors.index');
    }
}

resources/views/doctors/drug/index.blade.php
@extends('doctors.layouts.master')
@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">SOFT PHARM "MCHJ" bazasidagi dorilar</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">

                        </ul>
                    </div>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block card-dashboard">
                        <p>Add <code class="highlighter-rouge">.table-hover</code> to enable a hover state on table rows within a <code class="highlighter-rouge">&lt;tbody&gt;</code>.</p>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-hover mb-0">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Dori nomi</th>
                                <th>Soni</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($drugs as $key => $drug)
                                <tr>
                                    <th scope="row">{{$key}}</th>
                                    <td>{{$drug->drug_title}}</td>
                                    <td>{{$drug->drug_all}}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/doctors/index.blade.php
@extends('doctors.layouts.master')
@section('content')
    hi admin
@endsection

resources/views/doctors/partials/navbar.blade.php
<nav class="header-navbar navbar navbar-with-menu navbar-fixed-top navbar-semi-dark navbar-shadow">
    <div class="navbar-wrapper">
        <div class="navbar-header">
            <ul class="nav navbar-nav">
                <li class="nav-item mobile-menu hidden-md-up float-xs-left"><a class="nav-link nav-menu-main menu-toggle hidden-xs"><i class="icon-menu5 font-large-1"></i></a></li>
                <li class="nav-item"><a href="index.html" class="navbar-brand nav-link"><img alt="branding logo" src="{{asset('auth/app-assets/images/logo/robust-logo-light.png')}}" data-expand="{{asset('auth/app-assets/images/logo/robust-logo-light.png')}}" data-collapse="{{asset('auth/app-assets/images/logo/robust-logo-small.png')}}" class="brand-logo"></a></li>
                <li class="nav-item hidden-md-up float-xs-right"><a data-toggle="collapse" data-target="#navbar-mobile" class="nav-link open-navbar-container"><i class="icon-ellipsis pe-2x icon-icon-rotate-right-right"></i></a></li>
            </ul>
        </div>
        <div class="navbar-container content container-fluid">
            <div id="navbar-mobile" class="collapse navbar-toggleable-sm">
                <ul class="nav navbar-nav">
                </ul>
                <ul class="nav navbar-nav float-xs-right">

                    <li class="dropdown dropdown-user nav-item">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle nav-link dropdown-user-link">
                            <span class="avatar avatar-online">
                                <img src="{{asset('auth/app-assets/images/portrait/small/avatar-s-1.png')}}" alt="avatar">
                                <i></i>
                            </span>
                            <span class="user-name">Akhmedov</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a href="#" class="dropdown-item"><i class="icon-head"></i> Edit Profile</a>

                            <div class="dropdown-divider"></div>

                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                <i class="icon-power3"></i> {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

resources/views/doctors/partials/sidebar.blade.php
<div class="main-menu-content">
    <ul id="main-menu-navigation" data-menu="menu-navigation" class="navigation navigation-main">

        <li class=" nav-item">
            <a href="#">
                <i class="icon-file-add"></i>
                <span data-i18n="nav.page_layouts.main" class="menu-title">Retsept</span>
            </a>
            <ul class="menu-content {{(request()->routeIs('recipe.create') || request()->routeIs('recipe.index')) ? 'd-block' : ''}}">
                <li><a style="color: {{request()->routeIs('recipe.create') ? "#7366ff" : ""}}" href="{{route('recipe.create')}}" data-i18n="nav.page_layouts.1_column" class="menu-item">retsept yaratish</a>
                </li>
                <li><a style="color: {{request()->routeIs('recipe.index') ? "#7366ff" : ""}}" href="{{route('recipe.index')}}" data-i18n="nav.page_layouts.2_columns" class="menu-item">retseptlar ro'yxati</a>
                </li>
            </ul>
        </li>

        <li class=" nav-item">
            <a href="#">
                <i class="icon-basecamp"></i>
                <span data-i18n="nav.page_layouts.main" class="menu-title">Bazdagi dorilar</span>
            </a>
            <ul class="menu-content {{(request()->routeIs('drug.view')) ? 'd-block' : ''}}">
                <li><a style="color: {{request()->routeIs('drug.view') ? "#7366ff" : ""}}" href="{{route('drug.view')}}" data-i18n="nav.page_layouts.1_column" class="menu-item">dorilar ro'yxati</a>
                </li>
            </ul>
        </li>

    </ul>
</div>

resources/views/doctors/recipe/create.blade.php
@extends('doctors.layouts.master')
@section('content')
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title" id="basic-layout-card-center">Bemorga yoziladigan dorilar</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">

                        </ul>
                    </div>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block">
                        <div class="card-text">
                            <p>Ushbu yozilgan dorilar ro'yxati doimo nazoratda turadi.Ushbu yozilgan dorilar ro'yxati doimo nazoratda turadi.Ushbu yozilgan dorilar ro'yxati doimo nazoratda turadi.Ushbu yozilgan dorilar ro'yxati doimo nazoratda turadi.</p>
                        </div>
                        <form class="form" action="{{route('recipe.store')}}" method="post">
                            @csrf
                            <div class="form-body">
                                <div class="form-group">
                                    <label for="eventRegInput1">Dori nomi</label>
                                    <select name="drug_name" id="projectinput6" name="budget" class="form-control">
                                        @foreach($drugs as $drug)
                                            <option value="{{$drug->id}}">{{$drug->drug_title}}</option>
                                        @endforeach
                                    </select>
{{--                                    <select class="form-select" name="drug_name" id="">--}}

{{--                                    </select>--}}
{{--                                    <input type="text" id="eventRegInput1" class="form-control" placeholder="nomlanishi" name="drug_name">--}}
                                </div>

                                <div class="form-group">
                                    <label for="eventRegInput2">Dozasi</label>
                                    <input type="text" id="eventRegInput2" class="form-control" placeholder="dozasi" name="drug_doze">
                                </div>

                                <div class="form-group">
                                    <label for="eventRegInput3">Soni</label>
                                    <input type="text" id="eventRegInput3" class="form-control" placeholder="nechta kerak" name="drug_count">
                                </div>

                                <div class="form-group">
                                    <label for="eventRegInput3">Bemor FIO</label>
                                    <input type="text" id="eventRegInput3" class="form-control" placeholder="bemor ismi familiyasi" name="patient">
                                </div>

                            </div>

                            <div class="form-actions center">
                                <button type="submit" class="btn btn-primary">
                                    <i class="icon-check2"></i> Retseptni yaratish
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/doctors/recipe/index.blade.php
@extends('doctors.layouts.master')
@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Bemorlarga siz tomoningizdan yozilgan retseptlar</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">

                        </ul>
                    </div>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block card-dashboard">
                        <p>Add <code class="highlighter-rouge">.table-hover</code> to enable a hover state on table rows within a <code class="highlighter-rouge">&lt;tbody&gt;</code>.</p>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-hover mb-0">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Dori nomi</th>
                                <th>Dozasi</th>
                                <th>Soni</th>
                                <th>Bemor</th>
                                <th>Qr code</th>
                                <th>Scan</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($recipes as $key => $recipe)
                            <tr>
                                <th scope="row">{{$key}}</th>
                                <td>{{$recipe->drug_title}}</td>
                                <td>{{$recipe->drug_doze}}</td>
                                <td>{{$recipe->drug_count}}</td>
                                <td>
                                    <a href="{{route('show.retsept', $recipe->asosiy)}}">{{$recipe->patient}}</a>
                                </td>
                                <td>
                                    {{QrCode::size(300)->format('svg')->generate(route('show.retsept',$recipe->asosiy), public_path('doctors/qrcodes/'.$recipe->recipe_qrcode))}}
                                    <img width="70" height="70" src="{{asset('doctors/qrcodes/'.$recipe->recipe_qrcode)}}" alt="">
                                </td>
                                <td>{{$recipe->qrcode_scan}}</td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/main/view.blade.php
<!DOCTYPE html>
<html lang="en" data-textdirection="ltr" class="loading">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Robust admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, robust admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="PIXINVENT">
    <title>Doctor dashboard</title>
    <link rel="apple-touch-icon" sizes="60x60" href="{{asset('auth/app-assets/images/ico/apple-icon-60.png')}}">
    <link rel="apple-touch-icon" sizes="76x76" href="{{asset('auth/app-assets/images/ico/apple-icon-76.png')}}">
    <link rel="apple-touch-icon" sizes="120x120" href="{{asset('auth/app-assets/images/ico/apple-icon-120.png')}}">
    <link rel="apple-touch-icon" sizes="152x152" href="{{asset('auth/app-assets/images/ico/apple-icon-152.png')}}">
    <link rel="shortcut icon" type="image/x-icon" href="{{asset('auth/app-assets/images/ico/favicon.ico')}}">
    <link rel="shortcut icon" type="image/png" href="{{asset('auth/app-assets/images/ico/favicon-32.png')}}">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <link rel="stylesheet" type="text/css" href="{{asset('auth/app-assets/css/bootstrap.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('auth/app-assets/fonts/icomoon.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('auth/app-assets/fonts/flag-icon-css/css/flag-icon.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('auth/app-assets/vendors/css/extensions/pace.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('auth/app-assets/css/bootstrap-extended.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('auth/app-assets/css/app.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('auth/app-assets/css/colors.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('auth/app-assets/css/core/menu/menu-types/vertical-menu.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('auth/app-assets/css/core/menu/menu-types/vertical-overlay-menu.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('auth/app-assets/css/core/colors/palette-gradient.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('auth/assets/css/style.css')}}">
</head>
<body>

<br>
@if($retseptlar[0]->qrcode_scan == 0)
<div style="width: 100%; display: flex; justify-content: center">
<div class="col-xl-4 col-md-6 col-sm-12">
    <div class="card" style="height: auto;">
        <div class="card-body">
            <div class="card-block">
                <h4 class="card-title">{{$retseptlar[0]->patient}}</h4>
                <p class="card-text">Ushbu bemorga berilgan dorilar ro'yxati</p>
            </div>
            <ul class="list-group">
                <li class="list-group-item">
                    Dori nomi : &nbsp;
                    <span class="tag tag-default tag-pill bg-primary">
{{--                        @if($retseptlar[0]->drug_name == 1)--}}
{{--                            stramon--}}
{{--                        @elseif($retseptlar[0]->drug_name == 2)--}}
{{--                            fanigan--}}
{{--                        @elseif($retseptlar[0]->drug_name == 3)--}}
{{--                            pensilin--}}
{{--                        @endif--}}
                        {{$retseptlar[0]->drug_title}}
                    </span>

                </li>
                <li class="list-group-item">
                    Dori dozasi :
                    <span class="tag tag-default tag-pill bg-info">{{$retseptlar[0]->drug_doze}}</span>

                </li>
                <li class="list-group-item">
                    Dori soni : &nbsp;&nbsp;
                    <span class="tag tag-default tag-pill bg-warning">{{$retseptlar[0]->drug_count}} dona</span>

                </li>

            </ul>
            <div class="card-block">
                <a href="{{route('sell.drug', $retseptlar[0]->asosiy)}}" class="btn btn-success">Dorini sotish</a>
            </div>
        </div>
    </div>
</div>
</div>
@elseif($retseptlar[0]->qrcode_scan == 1)
    <div style="width: 100%; display: flex; justify-content: center">
        <div class="col-xl-4 col-md-6 col-sm-12">
            <div class="card" style="height: auto;">
                <div class="card-body">
                    <div class="card-block">
                        <h4 class="card-title">{{$retseptlar[0]->patient}}</h4>
                        <span class="tag tag-default tag-pill bg-primary">Ushbu bemorga berilgan dorilar barchasi sotilgan</span>
                    </div>
                    <ul class="list-group">


                    </ul>
                    <div class="card-block">
                    </div>
                </div>
            </div>
        </div>
    </div>
@endif

<script src="{{asset('auth/app-assets/js/core/libraries/jquery.min.js')}}" type="text/javascript"></script>
<script src="{{asset('auth/app-assets/vendors/js/ui/tether.min.js')}}" type="text/javascript"></script>
<script src="{{asset('auth/app-assets/js/core/libraries/bootstrap.min.js')}}" type="text/javascript"></script>
<script src="{{asset('auth/app-assets/vendors/js/ui/perfect-scrollbar.jquery.min.js')}}" type="text/javascript"></script>
<script src="{{asset('auth/app-assets/vendors/js/ui/unison.min.js')}}" type="text/javascript"></script>
<script src="{{asset('auth/app-assets/vendors/js/ui/blockUI.min.js')}}" type="text/javascript"></script>
<script src="{{asset('auth/app-assets/vendors/js/ui/jquery.matchHeight-min.js')}}" type="text/javascript"></script>
<script src="{{asset('auth/app-assets/vendors/js/ui/screenfull.min.js')}}" type="text/javascript"></script>
<script src="{{asset('auth/app-assets/vendors/js/extensions/pace.min.js')}}" type="text/javascript"></script>
<script src="{{asset('auth/app-assets/vendors/js/charts/chart.min.js')}}" type="text/javascript"></script>
<script src="{{asset('auth/app-assets/js/core/app-menu.js')}}" type="text/javascript"></script>
<script src="{{asset('auth/app-assets/js/core/app.js')}}" type="text/javascript"></script>
<script src="{{asset('auth/app-assets/js/scripts/pages/dashboard-lite.js')}}" type="text/javascript"></script>
</body>
</html>